---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
    tag: "latest"

inputs:
  - name: git-repo

run:
  path: git-repo/ci/scripts/db-update.sh

params:
  CF_API: 
  CF_USER:
  CF_PASS:
  CF_TEST_ORG:
  CF_TEST_SPACE:
